import { prisma } from "@/lib/prisma";

const statements = [
  `CREATE TABLE IF NOT EXISTS traffic_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path varchar(512) NOT NULL,
    visitor_hash varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_traffic_events_created_at_desc ON traffic_events (created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_traffic_events_path_created_at_desc ON traffic_events (path, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_traffic_events_visitor_hash_created_at_desc ON traffic_events (visitor_hash, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_products_created_at_id_desc ON products (created_at DESC, id DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_products_updated_at_id_desc ON products (updated_at DESC, id DESC)`
];

async function main() {
  for (const statement of statements) {
    await prisma.$executeRawUnsafe(statement);
  }

  console.log("Performance schema ensured.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
